[workspace]
resolver = "2"
members = [
    "crates/ols-core",
    "crates/ols-helper",
    "crates/ols-cli",
    "src-tauri",
]

[workspace.package]
version = "1.0.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/openlocalserver/openlocalserver"

[profile.dev]
incremental = true
