[workspace]
resolver = "2"
members = [
    "crates/ols-core",
    "crates/ols-helper",
    "crates/ols-cli",
    "src-tauri",
]

[workspace.package]
version = "1.1.1"
edition = "2021"
license = "GPL-3.0-only"
authors = ["Khaled Morsi"]
repository = "https://github.com/kz370/OpenLocalServer"

[profile.dev]
incremental = true
