//! ols-core: the application core (§8.1). GUI, CLI, and the future local API are all
//! front doors onto this crate — none of them talk to a manager directly.

pub mod ai;
pub mod api;
pub mod app;
pub mod ca;
pub mod catalog;
pub mod catalogs;
pub mod certs;
pub mod command;
pub mod command_catalog;
pub mod composer;
pub mod control;
pub mod custom_install;
pub mod custom_service;
pub mod dbbackup;
pub mod dbtools;
pub mod detection;
pub mod diagnostics;
pub mod dns;
pub mod editors;
pub mod envfile;
pub mod domain;
pub mod elevate;
pub mod error;
pub mod exec;
pub mod git;
pub mod health;
pub mod hosts;
pub mod inspector;
pub mod journal;
pub mod loadtest;
pub mod logging;
pub mod mail;
pub mod manifest;
pub mod migrate;
pub mod monitor;
pub mod network;
pub mod nodepm;
pub mod paths;
pub mod php;
pub mod plugin;
pub mod port;
pub mod process;
pub mod profiles;
pub mod project;
pub mod project_tools;
pub mod quickapp;
pub mod redact;
pub mod repair;
pub mod resolver;
pub mod resources;
pub mod runtime;
pub mod scheduler;
pub mod search;
pub mod secrets;
pub mod service;
pub mod setup;
pub mod settings;
pub mod shell_menu;
pub mod shortcuts;
pub mod snapshots;
pub mod sqlite;
pub mod support;
pub mod terminal;
pub mod tunnel;
pub mod updater;
pub mod venv;
pub mod web;
pub mod workers;
pub mod xdebug;
#[cfg(test)]
mod test_support;

pub use command::{Core, CoreCommand, CoreResponse};
pub use error::{CoreError, Diagnostic};
pub use paths::AppPaths;
pub use process::ProcessSupervisor;
pub use project::ProjectStore;
pub use runtime::RuntimeManager;
pub use service::ServiceManager;
pub use settings::SettingsService;
