//! PHP FastCGI pools (§11, Stage 6): one supervised set of `php-cgi` workers per PHP
//! version. Each site's `fastcgi_pass` targets the pool of the version it resolves to, so
//! `a.test` can run 8.1 while `b.test` runs 8.4 on the same machine at the same time.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use serde::{Deserialize, Serialize};

use crate::paths::AppPaths;
use crate::process::{ProcessId, ProcessSpec, ProcessSupervisor, RestartPolicy};
use crate::runtime::RuntimeManager;

/// Extensions enabled when their DLL exists in the install's `ext/` folder — the set
/// Laravel, Symfony and WordPress ask for on install (§154).
const EXTENSIONS: &[&str] = &[
    "curl", "fileinfo", "gd", "intl", "mbstring", "exif", "mysqli", "openssl", "pdo_mysql", "pdo_sqlite", "sqlite3",
    "zip", "sodium", "bcmath", "soap", "gettext",
];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PoolStatus {
    pub version: String,
    pub ports: Vec<u16>,
    pub running: bool,
}

struct Pool {
    version: String,
    ports: Vec<u16>,
    processes: Vec<ProcessId>,
}

pub struct PhpPools {
    paths: AppPaths,
    runtimes: Arc<RuntimeManager>,
    supervisor: Arc<ProcessSupervisor>,
    pools: Mutex<HashMap<String, Pool>>,
    /// PHP installs the user pointed at (version -> `php.exe`), alongside the managed ones.
    external: Mutex<HashMap<String, PathBuf>>,
}

impl PhpPools {
    pub fn new(paths: AppPaths, runtimes: Arc<RuntimeManager>, supervisor: Arc<ProcessSupervisor>) -> Self {
        Self { paths, runtimes, supervisor, pools: Mutex::new(HashMap::new()), external: Mutex::new(HashMap::new()) }
    }

    /// Replaces the set of user-registered PHP installs (version label -> `php.exe`).
    pub fn set_external(&self, entries: Vec<(String, PathBuf)>) {
        *self.external.lock().unwrap() = entries.into_iter().collect();
    }

    /// Managed plus user-registered versions.
    pub fn all_versions(&self) -> Vec<String> {
        let mut all = self.runtimes.installed_versions("php");
        for v in self.external.lock().unwrap().keys() {
            if !all.contains(v) {
                all.push(v.clone());
            }
        }
        all
    }

    /// The folder holding `php.exe`, `php-cgi.exe` and `ext/` for `version`.
    fn install_dir_of(&self, version: &str) -> PathBuf {
        match self.external.lock().unwrap().get(version).and_then(|exe| exe.parent()) {
            Some(dir) => dir.to_path_buf(),
            None => self.runtimes.install_dir("php", version),
        }
    }

    /// Which installed PHP satisfies `requested` ("8.1" or "8.1.34" or None = newest)?
    pub fn pick_version(&self, requested: Option<&str>) -> Option<String> {
        pick_version(&self.all_versions(), requested)
    }

    /// Name-safe pool id for a full version: "8.1.34" → "php_81".
    pub fn pool_id(version: &str) -> String {
        let mut parts = version.split('.');
        format!("php_{}{}", parts.next().unwrap_or("0"), parts.next().unwrap_or("0"))
    }

    /// Deterministic ports so a restart reuses the same ones: 10000 + major*100 + minor*10 + worker.
    fn ports_for(version: &str, workers: u16) -> Vec<u16> {
        let mut parts = version.split('.').map(|p| p.parse::<u16>().unwrap_or(0));
        let (major, minor) = (parts.next().unwrap_or(8), parts.next().unwrap_or(0));
        let base = 10_000 + major * 100 + minor * 10;
        (0..workers.clamp(1, 10)).map(|w| base + w).collect()
    }

    /// The directory holding this version's generated `php.ini`. Passing it as `PHPRC` makes
    /// both `php-cgi` and CLI `php` (Composer!) load it.
    pub fn ini_dir(&self, version: &str) -> PathBuf {
        self.paths.services_dir().join("php").join(version)
    }

    /// Writes a php.ini enabling the extensions this install actually ships.
    pub fn write_ini(&self, version: &str) -> Result<PathBuf, String> {
        let install = self.install_dir_of(version);
        let ext_dir = install.join("ext");
        let mut ini = String::new();
        ini.push_str("; Generated by OpenLocalServer - regenerated on every start.\n[PHP]\n");
        ini.push_str(&format!("extension_dir = \"{}\"\n", ext_dir.display().to_string().replace('\\', "/")));
        ini.push_str("display_errors = On\nerror_reporting = E_ALL\nmemory_limit = 512M\n");
        ini.push_str("upload_max_filesize = 128M\npost_max_size = 128M\nmax_execution_time = 120\n");
        ini.push_str("date.timezone = UTC\ncgi.fix_pathinfo = 1\ncgi.force_redirect = 0\nfastcgi.impersonate = 1\n");
        // PHP's mail() on Windows speaks SMTP directly — point it at Mailpit (§63).
        ini.push_str(&format!("SMTP = 127.0.0.1\nsmtp_port = {}\nsendmail_from = dev@localhost\n", crate::service::mailpit_smtp_port()));
        for ext in EXTENSIONS {
            if ext_dir.join(format!("php_{ext}.dll")).is_file() {
                ini.push_str(&format!("extension={ext}\n"));
            }
        }
        let dir = self.ini_dir(version);
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        std::fs::write(dir.join("php.ini"), ini).map_err(|e| e.to_string())?;
        Ok(dir)
    }

    /// Ensures `workers` php-cgi processes are up for `version`; returns their ports.
    pub fn ensure(&self, version: &str, workers: u16) -> Result<Vec<u16>, String> {
        let ports = Self::ports_for(version, workers);
        let mut pools = self.pools.lock().unwrap();
        if let Some(existing) = pools.get(version) {
            let all_alive = existing.processes.iter().all(|p| self.supervisor.is_alive(*p));
            if existing.ports == ports && all_alive {
                return Ok(ports);
            }
            // Wrong size or a dead worker: rebuild the whole pool so the ports line up.
            for id in &existing.processes {
                self.supervisor.stop(*id);
            }
            pools.remove(version);
        }

        let binary = self.install_dir_of(version).join("php-cgi.exe");
        if !binary.is_file() {
            return Err(format!("php-cgi.exe is missing from PHP {version}"));
        }
        let ini_dir = self.write_ini(version)?;

        let mut processes = Vec::new();
        for port in &ports {
            let id = self.supervisor.start(ProcessSpec {
                name: format!("PHP {version} FastCGI :{port}"),
                executable: binary.display().to_string(),
                args: vec!["-b".into(), format!("127.0.0.1:{port}")],
                cwd: None,
                env: vec![
                    ("PHPRC".into(), ini_dir.display().to_string()),
                    ("PHP_FCGI_MAX_REQUESTS".into(), "0".into()),
                ],
                restart: Some(RestartPolicy { max_retries: 5, delay_ms: 1000 }),
            });
            processes.push(id);
        }
        pools.insert(version.to_string(), Pool { version: version.to_string(), ports: ports.clone(), processes });
        Ok(ports)
    }

    pub fn stop_all(&self) {
        let mut pools = self.pools.lock().unwrap();
        for (_, pool) in pools.drain() {
            for id in pool.processes {
                self.supervisor.stop(id);
            }
        }
    }

    /// Stops pools for versions not in `keep` (a version no site uses any more).
    pub fn retain(&self, keep: &[String]) {
        let mut pools = self.pools.lock().unwrap();
        let stale: Vec<String> = pools.keys().filter(|v| !keep.contains(v)).cloned().collect();
        for version in stale {
            if let Some(pool) = pools.remove(&version) {
                for id in pool.processes {
                    self.supervisor.stop(id);
                }
            }
        }
    }

    pub fn status(&self) -> Vec<PoolStatus> {
        let pools = self.pools.lock().unwrap();
        let mut list: Vec<PoolStatus> = pools
            .values()
            .map(|p| PoolStatus {
                version: p.version.clone(),
                ports: p.ports.clone(),
                running: p.processes.iter().all(|id| self.supervisor.is_alive(*id)),
            })
            .collect();
        list.sort_by(|a, b| a.version.cmp(&b.version));
        list
    }
}

/// A PHP install found by [`scan_folder`].
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ScannedPhp {
    pub version: String,
    pub php_exe: String,
}

/// Finds PHP installs under `dir`: the folder itself and every folder up to two levels
/// below it that holds both `php.exe` and `php-cgi.exe` (a Laragon-style `bin/php/php-8.4.22...`
/// layout works when pointed at either `bin` or `php`). Versions come from `php -v`, so
/// folder names don't matter.
pub fn scan_folder(dir: &std::path::Path) -> Vec<ScannedPhp> {
    fn candidates(dir: &std::path::Path, depth: u8, out: &mut Vec<PathBuf>) {
        if dir.join("php.exe").is_file() && dir.join("php-cgi.exe").is_file() {
            out.push(dir.to_path_buf());
            return;
        }
        if depth == 0 {
            return;
        }
        if let Ok(rd) = std::fs::read_dir(dir) {
            let mut kids: Vec<PathBuf> = rd.flatten().map(|e| e.path()).filter(|p| p.is_dir()).collect();
            kids.sort();
            for kid in kids {
                candidates(&kid, depth - 1, out);
            }
        }
    }
    let mut dirs = Vec::new();
    candidates(dir, 2, &mut dirs);
    let mut found = Vec::new();
    for d in dirs {
        let exe = d.join("php.exe");
        let out = crate::exec::run_capture(&exe, &["-v".to_string()], None, &[], std::time::Duration::from_secs(10));
        if let Some(version) = parse_php_version(&out.stdout) {
            found.push(ScannedPhp { version, php_exe: exe.display().to_string() });
        }
    }
    found
}

/// "PHP 8.4.22 (cli) (built: ...)" gives "8.4.22".
fn parse_php_version(output: &str) -> Option<String> {
    let rest = output.lines().next()?.trim().strip_prefix("PHP ")?;
    let version = rest.split_whitespace().next()?;
    version.chars().next().is_some_and(|c| c.is_ascii_digit()).then(|| version.to_string())
}

/// "8.1" matches "8.1.34"; None (or an exact version) picks accordingly; newest wins ties.
pub fn pick_version(installed: &[String], requested: Option<&str>) -> Option<String> {
    let mut candidates: Vec<&String> = match requested {
        Some(req) if !req.is_empty() => {
            let prefix = format!("{req}.");
            installed.iter().filter(|v| v.as_str() == req || v.starts_with(&prefix)).collect()
        }
        _ => installed.iter().collect(),
    };
    candidates.sort_by_key(|v| version_key(v));
    candidates.last().map(|v| (*v).clone())
}

fn version_key(version: &str) -> Vec<u32> {
    version.split('.').map(|p| p.parse().unwrap_or(0)).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(list: &[&str]) -> Vec<String> {
        list.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn parses_the_version_out_of_php_dash_v() {
        assert_eq!(parse_php_version("PHP 8.4.22 (cli) (built: Jul  1 2026) (NTS)\nCopyright").as_deref(), Some("8.4.22"));
        assert_eq!(parse_php_version("PHP 8.5.0-dev (cli)").as_deref(), Some("8.5.0-dev"));
        assert_eq!(parse_php_version("not php"), None);
    }

    #[test]
    fn scan_ignores_folders_without_php_cgi_and_survives_unrunnable_binaries() {
        let root = tempfile::tempdir().unwrap();
        let fake = root.path().join("php").join("php-8.1");
        std::fs::create_dir_all(&fake).unwrap();
        std::fs::write(fake.join("php.exe"), "").unwrap();
        std::fs::write(fake.join("php-cgi.exe"), "").unwrap();
        let cli_only = root.path().join("php").join("cli-only");
        std::fs::create_dir_all(&cli_only).unwrap();
        std::fs::write(cli_only.join("php.exe"), "").unwrap();
        // Empty stand-ins can't report a version, so nothing is registered and nothing panics.
        assert!(scan_folder(root.path()).is_empty());
    }

    #[test]
    fn pick_version_matches_minor_prefix_and_defaults_to_newest() {
        let installed = v(&["8.1.34", "8.4.26", "8.4.9"]);
        assert_eq!(pick_version(&installed, Some("8.1")).as_deref(), Some("8.1.34"));
        assert_eq!(pick_version(&installed, Some("8.4")).as_deref(), Some("8.4.26"), "8.4.26 > 8.4.9 numerically");
        assert_eq!(pick_version(&installed, Some("8.4.9")).as_deref(), Some("8.4.9"));
        assert_eq!(pick_version(&installed, None).as_deref(), Some("8.4.26"));
        assert_eq!(pick_version(&installed, Some("7.4")), None);
        assert_eq!(pick_version(&installed, Some("8.4.2")), None, "'8.4.2' must not prefix-match '8.4.26'");
    }

    #[test]
    fn pool_ids_and_ports_are_stable_and_distinct_per_minor_version() {
        assert_eq!(PhpPools::pool_id("8.1.34"), "php_81");
        let a = PhpPools::ports_for("8.1.34", 3);
        let b = PhpPools::ports_for("8.4.26", 3);
        assert_eq!(a, vec![10810, 10811, 10812]);
        assert!(a.iter().all(|p| !b.contains(p)));
    }
}
